INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (1, 'Notebook');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (2, 'Smartphone');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (3, 'TV');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (4, 'Tablet');
